version: 0.2

phases:
  install:
    run-as: root
    commands:
      - apk add --update py-pip
      - pip3 install --upgrade --user awscli
      - PATH=$PATH:/root/.local/bin
      - apk add wkhtmltopdf
  pre_build:
    run-as: root
    commands:
      - mkdir _site
      - chmod 777 _site
      - mkdir .jekyll-cache
      - chmod 777 .jekyll-cache
  build:
    run-as: root
    commands:
      - jekyll build
      - wkhtmltopdf --viewport-size 2000x2000 --orientation Portrait --page-size A4 --margin-bottom 1  --margin-left 1 --margin-right 1 --margin-top 1 file:///Users/mug/Microsoft/OneDrive%20-%20studenti.unisa.it/Progetti/online-cv/_site/index.html output.pdf
  post_build:
    commands:
      - aws s3 cp ./_site s3://$BUCKET_NAME/$PREFIX --acl public-read --recursive