version: 0.2

phases:
  install:
    run-as: root
    commands:
      - apk add --update py-pip
      - pip install --upgrade --user awscli
      - PATH=$PATH:/root/.local/bin
  build:
    run-as: root
    commands:
      - wkhtmltopdf --viewport-size 2000x2000 --orientation Portrait --page-size A4 --margin-bottom 1  --margin-left 1 --margin-right 1 --margin-top 1 --javascript-delay 1000 $SITE vitae.pdf
  post_build:
    commands:
      - aws s3 cp ./vitae.pdf s3://$BUCKET_NAME/$PREFIX/vitae.pdf --acl public-read