version: 0.2

phases:
  install:
    run-as: root
    commands:
      - apk add --update py-pip
      - pip install --upgrade --user awscli==1.19.112
      - PATH=$PATH:/root/.local/bin
  build:
    run-as: root
    commands:
      - wkhtmltopdf --viewport-size 2000x2000 --orientation Portrait --page-size A4 --margin-bottom 0  --margin-left 0 --margin-right 0 --margin-top 0 --javascript-delay 2000 $SITE vitae.pdf
  post_build:
    commands:
      - aws s3 cp ./vitae.pdf s3://$BUCKET_NAME/$PREFIX/vitae.pdf --acl public-read
